### ISSUE TITLE
Chrome blocks download 

### ISSUE THREAD

**Issue by bmackinney** [babun/babun#464] opened 2015-09-28 05:31 UTC
Tried from yer github pages site, to get http://projects.reficio.org/babun/download to no avail. 
Google  thinks Babun is malware. More info from the menu leads to: https://support.google.com/chrome/answer/6261569?p=ib_download_blocked&hl=en&rd=1
![image](https://cloud.githubusercontent.com/assets/646061/10128424/50f0b014-6567-11e5-9f93-65a7d5c32c49.png)

**Comment by divmgl** [comment] 2015-09-28 16:37
+1, what's with this?

**Comment by tombujok** [comment] 2015-09-28 16:45
No idea. Feedback appreciated

**Comment by bmackinney** [comment] 2015-09-28 17:22
They link to this page for developers at the link in the OP. https://support.google.com/webmasters/answer/3258249

**Comment by mstanescu** [comment] 2015-09-28 17:30
same here, cannot figure out whats causing it because not much details are given

**Comment by radnor** [comment] 2015-10-07 15:36
You can recover the downloaded file by viewing your downloads (`Control-J` or `Shift-Command-J`) and clicking on the `Recover malicious file` link beneath the file.

![image](https://cloud.githubusercontent.com/assets/53380/10342563/7579c3bc-6cce-11e5-99d9-e1600668d4ea.png)

**Comment by divmgl** [comment] 2015-10-10 00:32
Any word on this? Why is it flagged? I 'm kind of scared to download it.

**Comment by radnor** [comment] 2015-10-12 17:19
I imagine it's flagged because the zip contains a number of executables and vbscript files. Chrome is just being overly cautious.

**Comment by KOGI** [comment] 2015-10-14 21:10
Nice workaround @radnor !

**Comment by iirekm** [comment] 2015-10-17 15:42
Maybe Google blocked babun on purpose.
A few minutes after installing babun i noticed that Google search engine stopped working in Chrome when you enter search keywords in Chrome toolbar, but when you enter them inside google.com page it still works. Other engines like bing.com work normally, even when keywords are entered from toolbar. Maybe it's somehow related to this warning?

**Comment by gdw2** [comment] 2015-10-17 15:48
My chrome awesome-bar search still works.

I think babun only adds files to ~/.babun and nothing else.  I could be
wrong though.

**Comment by tombujok** [comment] 2015-10-17 15:49
@iirekm it's a coincidence

**Comment by tombujok** [comment] 2015-10-17 15:50
@jlupi Did you manage to upload the file requested by google to bintray to solve this problem once and for all?

**Comment by stevenengler** [comment] 2015-10-23 18:36
Just want to mention that I received this error today for babun-1.2.0-dist.zip.

**Comment by sethdmoore** [comment] 2015-10-25 23:50
Just ran into this

Google Chrome	47.0.2526.27 (Official Build) beta-m (64-bit)
Revision	74de6ccccb9d801946204f7facb5d600124cdc50-refs/branch-heads/2526@{#186}
Windows 10

I am not running into this with babun-1.1.1
[Screenshot](http://i.imgur.com/ZhXxoJc.png)

**Comment by kwinz** [comment] 2015-10-27 01:50
My download just got blocked by Chrome as well.

**Comment by ppetermann** [comment] 2015-10-30 20:03
same here

**Comment by jlupi** [comment] 2015-11-02 19:15
@tombujok The file was submitted but nothing changed so far. Not sure if the review process takes so long or something else is NOK. In the meantime I have added a message to the website with the information that such problem exists.

**Comment by Kerumen** [comment] 2015-11-03 22:03
Just downloaded latest zip with lates Chrome. Same issue.

**Comment by primeinc** [comment] 2015-11-06 06:41
works now!

**Comment by stela5** [comment] 2015-11-06 22:10
Still a problem for me.  How about trying a self-extracting 7-zip file?

**Comment by primeinc** [comment] 2015-11-06 22:27
I think the issue is dl.bintray.com has a lot of different programs hosted for download and every once and a while the domian gets flagged in general, I doubt Google actually thinks babun is malware.

https://www.google.com/transparencyreport/safebrowsing/diagnostic/#url=http://dl.bintray.com

This would explain why it works sometimes and other times doesn't.

**Comment by vsimonian** [comment] 2015-11-11 08:48
Was able to download babun just fine right now on Chrome 46.

**Comment by iampeterbanjo** [comment] 2015-11-12 20:16
I got the warning message today (Chrome 46)

**Comment by kevinhooke** [comment] 2015-11-19 01:53
Blocked for me too, Chrome 46

**Comment by MaxPRafferty** [comment] 2015-11-20 15:53
Download worked fine for me (Windows, Chrome 46.0.2490.86 m)

**Comment by shakeelmohamed** [comment] 2015-11-21 07:47
Thanks @radnor, that did the trick!

**Comment by michaelmior** [comment] 2015-11-24 05:40
Worked fine for me today.

**Comment by stevenengler** [comment] 2015-11-24 22:24
Chrome still blocks it for me.

**Comment by getaclue** [comment] 2015-11-26 20:50
:+1: Downloaded fine on ```Version 46.0.2490.86 m``` on ```Windows 8```

**Comment by ErickAgrazal** [comment] 2015-11-27 18:03
No issues here. 
Chrome Version: Versión 46.0.2490.86 m
OS: Windows 10 Pro

**Comment by MRebhan** [comment] 2015-12-01 19:12
Downloaded for me. Chrome 46.0.2490.86, Arch Linux. Looks like it's solved.

**Comment by toddprater** [comment] 2015-12-04 03:09
Still blocked for me (though I was able to 'recover' it.) Windows 10 Pro. Chrome 47.0.2526.73.

**Comment by alanyee** [comment] 2015-12-14 07:01
Also no issues here:
Chrome Version: 47.0.2526.80 m
OS: Windows 10 Pro

**Comment by eonardol** [comment] 2015-12-14 13:24
+1
Chrome Version: 47.0.2526.80 m
OS: Windows 7

**Comment by raucha** [comment] 2015-12-20 09:55
+1
Chrome version 47.0.2526.106 m (64-bit)
Windows 8.1

**Comment by phase** [comment] 2015-12-25 06:58
Works fine for me on Windows 10 using Chrome 47.0.2526.106. No blocks here.

**Comment by ZetaHunter** [comment] 2015-12-27 19:19
No blocks for me.

**Comment by mkumar118** [comment] 2015-12-29 10:04
downloads ok for me.
Chrome Version 47.0.2526.106 m
OS: Windows 10 Enterprise.

**Comment by GiGurra** [comment] 2015-12-30 11:49
still have the issue :S

**Comment by toddprater** [comment] 2015-12-30 20:21
Chrome 47.0.2526.106 m. Windows 10 Pro. Still blocked for me.

**Comment by darkoverlordofdata** [comment] 2016-01-07 17:39
Same issue in chrome 47/windows 7. I click  So I tried ff & opera. I didn't get an error message, but I also did not get a download. So I tried on Linux Mint with chrome 47. That worked. I copied the file to a thumb drive. Windows can't open the file, says invalid format.
I unpacked the zip on linux, repacked it, and walked it over to my windows machine. 
That worked.

**Comment by mostafaberg** [comment] 2016-01-11 21:03
Seems like some other IP/ASN that used to / is distributing malware, I did a quick check [here](http://urlquery.net/report.php?id=1452544592159) and if you scroll down to `
Recent reports on same IP/ASN/Domain` you'll see there are some reports there, some are benign and some have threats, perhaps hosting binaries on another server or getting a signed windows installer will fix this ?

**Comment by Fireflies** [comment] 2016-01-24 13:19
Google Chrome's beta build does not block the download on Windows 10.

![Chrome Build Number](http://i.imgur.com/5ZxKSEs.png)

**Comment by onlineth** [comment] 2016-01-26 16:30
Seems to be working for me

**Comment by timbru31** [comment] 2016-02-06 17:27
Chrome ``Version 48.0.2564.103 m (64-bit)`` works fine :)

**Comment by jonnybot0** [comment] 2016-02-09 16:13
I got blocked with the 1.2.0-dist.zip. @primeinc suggested the safe browsing checker, but both dl.bintry and [reficio](https://www.google.com/transparencyreport/safebrowsing/diagnostic/#url=http://projects.reficio.org/babun/download) are currently marked as "safe" in the Safe Browsing status site. For now, I'll just use Firefox. My guess is that this is some additional check beyond the hosting domain, or it would have blocked it outright at the beginning of the download, not at the end (after it had a chance to scan for unsigned script files).

**Comment by AlexejK** [comment] 2016-02-24 18:19
For me, `Chrome Version 48.0.2564.116 m (64bit)` worked just fine and opening a ZIP worked as expected.

**Comment by eko24** [comment] 2016-02-26 10:18
As said above `Windows 10 Chrome 48.0.2564.116 m (64bit)` also worked fine

**Comment by cjhmdm** [comment] 2016-03-09 04:35
Well, in case anyone is worried, virustotal scan came back clean:

https://www.virustotal.com/en/file/5dede288d8f2b150d8064a8bf31c6dbf2831ed04f9d9b55fd16600ce98b33a3e/analysis/1457498037/

**Comment by cheseaux** [comment] 2016-03-09 12:19
> Version 49.0.2623.87 m, Windows 8
Still blocked

**Comment by patrikbeno** [comment] 2016-03-11 14:56
`babun-1.2.0\dist\freespace.vbs`

^ that's it

If I remove it from *.zip, Chrome is OK
If I rename it it *.txt, Chrome is OK

So I guess you can find some workaround, @tombujok

**Comment by Chiel92** [comment] 2016-03-15 10:01
Downloading windows 7 with chrome fails, firefox downloads it just fine.

**Comment by adriannadiaz** [comment] 2016-03-16 14:22
Blocked also (Chrome + Windows 7), I think it has to do with the fact that it finds a .bat file inside the package.

**Comment by think01** [comment] 2016-04-12 21:41
Worked for me: babun-1.2.0-dist.zip, Chrome 49.0.2623.112 m, Windows 10 x64

**Comment by Gedankenleser** [comment] 2016-04-21 19:35
Here as well. It works! babun-1.2.0-dist.zip Version 50.0.2661.75 m (64-bit), windows 7 x64

**Comment by qwertzguy** [comment] 2016-04-21 21:00
Worked for me: Chrome 49.0.2623.112 m Windows 7 x64

**Comment by ericrdb** [comment] 2016-04-25 21:52
Confirmed. Working here too. 
Win 10
Chrome Version 49.0.2623.112 m

@tombujok: Recommend removing warning on homepage.

**Comment by cori** [comment] 2016-05-05 14:26
working fine on 2 different machine running Chrome 50.x

**Comment by kerstin** [comment] 2016-05-06 11:58
Just came here to report the same thing.
Downloaded fine using Windows 10 and Google Chrome 50.x

![babun_download](https://cloud.githubusercontent.com/assets/559572/15072288/252f36ce-1392-11e6-9983-84c3de6af264.png)

**Comment by waterfoul** [comment] 2016-05-31 19:53
Working for me

**Comment by BuildTheRobots** [comment] 2016-06-01 13:27
babun-1.2.0-dist.zip seems to download fine with Chrome "Version 50.0.2661.102 m"

**Comment by JimiHFord** [comment] 2016-06-13 18:58
worked for me 

Chrome Version 51.0.2704.84 m 
Windows 7

**Comment by jkudish** [comment] 2016-06-15 20:00
Worked for me babun-1.2.0.dist.zip on Windows 10
Chrome version 51.0.2704.84 (Official Build) m (64-bit)

**Comment by luisfego** [comment] 2016-06-17 21:59
Worked fine for me as well on Windows 7.
Chrome version 51.0.2704.84 m

**Comment by kerstin** [comment] 2016-06-18 10:47
@jlupi Do you think the PR I submitted (linked above) could be merged and this issue be closed?

**Comment by jarek-przygodzki** [comment] 2016-06-22 09:00
Works fine for me on Windows 10 Pro (10.0.10586) with Chrome 51.0.2704.103 m (babun-1.2.0-dist.zip).

Does anybody still experience this issue?

**Comment by kerstin** [comment] 2016-06-22 09:22
@jarek-przygodzki Not sure who your question is directed at. The people commenting in this thread obviosuly don't (; others won't be reading along here.

**Comment by exeQutor** [comment] 2016-07-03 10:56
Hi guys,

I got this working on Google Chrome. You just have to turn off Windows Firewall before you start your download. You can turn if back on again when you're done downloading and/or installing Babun.

You're welcome!

**Comment by remoharsono** [comment] 2016-07-22 23:15
work fine here on windows 8.1 (administrator account) / chrome 52.0.2743.82 m (64-bit) / babun-1.2.0.dist.zip

**Comment by vsimonian** [comment] 2016-07-22 23:19
Not to be too hasty, but since it seems like since April everyone has said that Chrome is downloading babun just fine now, shouldn't this issue get closed?

**Comment by kerstin** [comment] 2016-07-22 23:35
@vsimonian I assumed people continued to comment on here because the warning was still up on the website. (The most recent issue is no. 661, so this one here doesn't show up until searched for.) That said, my PR is still waiting to be merged...

**Comment by charlescva** [comment] 2016-07-28 16:26
"Works for me!"

Google Chrome	51.0.2704.106 (Official Build) m (32-bit)
Revision	27e9e15b411edc75a2233a9ad11dc7ae86e243fd-refs/branch-heads/2704_103@{#3}
OS	Windows 7 x64
JavaScript	V8 5.1.281.65
Flash	22.0.0.209
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Compiler	MSVC 2015

**Comment by jcdenton2k** [comment] 2016-08-21 16:26
Version 53.0.2785.8 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)'
Runs fine, works fine.

There are two settings in Privacy options that might be affecting this.
-Automatically report details of possible security incidents to Google
-Protect you and your device from dangerous sites

Other than that it is working fine for now if downloaded with a Linux system.

**Comment by svbeon** [comment] 2016-09-28 08:25
WFM

**Comment by mralext20** [comment] 2016-09-29 18:10
works fine for me, windows 10/ chrome 53.0.2785.116 (Official Build) m (64-bit)

**Comment by JPMSoftwire** [comment] 2016-10-03 12:49
Works fine for me as well now.

**Comment by iongion** [comment] 2016-10-12 05:42
Windows 10 Chrome Version 53.0.2785.143 m - all good, no malicious report

**Comment by jabocg** [comment] 2016-12-03 00:19
Works for me, took a while to *finalize* the download though.
```
Google Chrome	54.0.2840.99 (Official Build) m (64-bit)
Revision	7eca4ce1e662f12cadaf96c30cd2335fd03e7140-refs/branch-heads/2840@{#830}
OS	Windows 10 Home
JavaScript	V8 5.4.500.41
Flash	23.0.0.207
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
```

**Comment by dentych** [comment] 2016-12-12 18:20
Download worked fine for me. Tried it on both Windows 10 and Linux (Fedora). Chrome Version 54.0.2840.100 (64-bit)

**Closed** 2016-12-12 19:20 UTC

**Comment by avizmarlon** [comment] 2016-12-21 03:47
The issue seems resolved but the website still says: `Note: Chrome currently blocks the downloaded file. Please download using different browser until the problem is resolved.`

**Comment by wilomgfx** [comment] 2017-02-03 02:23
Works fine on chrome on windows and linux  btw.

**Comment by jlupi** [comment] 2017-02-05 13:10
@avizmarlon The warning was removed from the website. Thanks.

**Comment by ekumachidi** [comment] 2017-02-10 03:00
My download was blocked on chrome went to download lists to recover the file, but I mistakenly removed the blocked file from download lists, is there a way to find the file on windows?

**Comment by avizmarlon** [comment] 2017-02-10 12:06
The file was probably removed from windows when you removed it in the download list. Maybe you can recover with Recuva, but I think you should just download it again. Its easier.
