### ISSUE TITLE
When using tmux, numbers get printed on click

### ISSUE THREAD

**Issue by vjustov** [babun/babun#118] opened 2014-05-16 03:42 UTC
When i open tmux, it shows my prompt and random numbers
`vjustov@Sumaria:~$ 1;2`

on each following click, more random numbers get appended. 2c0;27;1m0;
i cannot copy because of this.

I got win 8.1, installed tmux using pact and im hashrockets dotfiles.

**Comment by tombujok** [comment] 2015-02-04 19:44
Duplicate of #123

**Closed by tombujok** 2015-02-04 19:44 UTC
Labels: feedback
