### ISSUE TITLE
Chrome (v. 47) blocks babun download as malicious

### ISSUE THREAD

**Issue by HyBRiD1492** [babun/babun#537] opened 2015-12-21 14:17 UTC
I Just downloaded babun and Chrome blocks it:
babun-1.2.0-dist.zip may harm your browsing experience, so Chrome has blocked it.

**Comment by sahat** [comment] 2016-01-16 09:50
Ran into the same issue, although it's pretty easy to bypass it in the Downloads (CTRL+J).

**Comment by feimosi** [comment] 2016-01-23 12:06
It's a known issue. Duplicate of #464

**Closed** 2016-01-28 10:38 UTC
