### ISSUE TITLE
Start in current working directory

### ISSUE THREAD

**Issue by LukaszWiktor** [babun/babun#131] opened 2014-05-19 10:29 UTC
Is it possible to set babun's working directory to the same location from which it was invoked? It would be very useful when I'm in a windows comman line (cmd.exe) and want to switch to babun and stay in the same directory. 

![image](https://cloud.githubusercontent.com/assets/2964543/3012909/2d4536a2-df40-11e3-99a5-a8f6713f2123.png)

**Comment by tombujok** [comment] 2015-02-04 20:27
Duplicate of #183

**Closed by tombujok** 2015-02-04 20:27 UTC
Labels: feedback

**Comment by soulcreate** [comment] 2016-01-11 20:52
Add in end of file "~/.babunrc"
```
cd /need/foolder/it
```

**Comment by ZenoArrow** [comment] 2016-01-19 12:05
@soulcreate Isn't part of the issue that the ~/.babunrc is being created from scratch on every new computer you use Babun on?

**Comment by r3b00t909** [comment] 2016-03-05 07:55
its working but actually shunt the "Open Babun Here" context menu entry

**Comment by Guiguillermo** [comment] 2016-09-19 08:45
To keep the "Open Babun Here" context menu entry working, you can add it to "~/.babunrc" :

if [ `pwd` = "[default_folder]" ]
then
        cd /need/foolder/it
fi

(default_folder should be your home folder : /home/[user]).
